### ISSUE TITLE
Thankyou!

### ISSUE THREAD

**Issue by markmuir87** [Doc-Cirrus/usb-tools#2]
@Doc-Cirrus, just wanted to say 'thanks!' for making this. I've been tearing my hair out in frustration trying to get my microserver updated so that ilo will actually work. Especially frustrating when every guide on updating firmware either starts with 'Log in to your ilo console...' or is spread out over 10 different 40 page PDFs on HP's god-awful site....

Anyhow, thanks again. I can finally get some sleep :)

**Comment by kosch** [comment]
Thanks, thats the exact reason why I made it public ;-)
