### ISSUE TITLE
USB can't boot with 2018 service pack

### ISSUE THREAD

**Issue by v0112358** [Doc-Cirrus/usb-tools#4]
Hi,

I have tested this script with 2018.03 service pack and it's not working as I expected.

**Comment by ooskapenaar** [comment]
As stated in the Readme, this utility requires Linux.

Closing ticket.

**Comment by kosch** [comment]
@mrmainnet I've not tested the current 2018 SPP, since they have refactored their layout. I'll test the 2018 legacy SPP in a few weeks.
